Repository Alfresco/alfresco-transform-core, pull requests merged in 2020-04, with the labels that each got.

#202 ATS-695 AIO T-Engine Spring Boot
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOController.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/Application.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/resources/application-default.yaml
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/resources/quick.html
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/resources/templates/transformForm.html
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerTest.java
  alfresco-transform-misc/alfresco-transform-misc-boot/Dockerfile
  pom.xml
Labels: PR: unreviewed

#205 Fix travis tests
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/test/resources/imagemagick_engine_config.json
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/test/resources/libreoffice_engine_config.json
  alfresco-transform-misc/alfresco-transform-misc-boot/src/main/resources/application-default.yaml
  alfresco-transform-misc/alfresco-transform-misc-boot/src/test/resources/misc_engine_config.json
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/src/test/resources/pdfrenderer_engine_config.json
  alfresco-transform-tika/alfresco-transform-tika-boot/src/main/resources/application-default.yaml
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/tika_engine_config.json
Labels: PR: reviewed-approved

#210 Refactor classes
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOController.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOCustomConfig.java
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/AIOTransformRegistry.java
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/transformers/AbstractTransformer.java
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/transformers/AllInOneTransformer.java
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/transformers/ImageMagickAdapter.java
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/transformers/LibreOfficeAdapter.java
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/transformers/MiscAdapter.java
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/transformers/PdfRendererAdapter.java
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/transformers/TikaAdapter.java
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/transformers/Transformer.java
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/test/java/org/alfresco/transformer/transformers/AllTransformRegistryTest.java
Labels: PR: unreviewed

#212 ATS-655: Update AIO java base image
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile
Labels: PR: partially-approved

#201 REPO-4919 - LibreOffice 6.3.5
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/Dockerfile
  alfresco-transform-libreoffice/alfresco-transform-libreoffice/src/main/java/org/alfresco/transformer/executors/LibreOfficeJavaExecutor.java
Labels: PR: reviewed-changes-requested

#203 ATS-669: Parameterize T-Engines transformer execution locations
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOCustomConfig.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/resources/application-default.yaml
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/transformers/ImageMagickAdapter.java
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/transformers/LibreOfficeAdapter.java
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/transformers/PdfRendererAdapter.java
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/pom.xml
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/main/java/org/alfresco/transformer/ImageMagickController.java
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/main/resources/application-default.yaml
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/test/java/org/alfresco/transformer/ImageMagickControllerTest.java
  alfresco-transform-imagemagick/alfresco-transform-imagemagick/src/main/java/org/alfresco/transformer/executors/ImageMagickCommandExecutor.java
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/pom.xml
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/main/java/org/alfresco/transformer/LibreOfficeController.java
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/main/resources/application-default.yaml
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/test/java/org/alfresco/transformer/LibreOfficeControllerTest.java
  alfresco-transform-libreoffice/alfresco-transform-libreoffice/src/main/java/org/alfresco/transformer/executors/LibreOfficeJavaExecutor.java
  alfresco-transform-misc/alfresco-transform-misc-boot/src/main/resources/application-default.yaml
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/pom.xml
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/src/main/java/org/alfresco/transformer/AlfrescoPdfRendererController.java
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/src/main/resources/application-default.yaml
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/src/test/java/org/alfresco/transformer/AlfrescoPdfRendererControllerTest.java
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer/src/main/java/org/alfresco/transformer/executors/PdfRendererCommandExecutor.java
  alfresco-transform-tika/alfresco-transform-tika-boot/src/main/resources/application-default.yaml
  alfresco-transformer-base/src/main/java/org/alfresco/transformer/TransformRegistryImpl.java
  alfresco-transformer-base/src/main/java/org/alfresco/transformer/executors/AbstractCommandExecutor.java
  alfresco-transformer-base/src/main/resources/application.yaml
  alfresco-transformer-base/src/test/java/org/alfresco/transformer/AbstractTransformerControllerTest.java
Labels: PR: reviewed-changes-requested

#208 ATS-702 Add AIOControllerTest for Imagemagick transforms
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOController.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerHttpRequestTest.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerImageMagickTest.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOImageMagickIT.java
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/pom.xml
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/test/java/org/alfresco/transformer/ImageMagickControllerTest.java
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/test/java/org/alfresco/transformer/ImageMagickTransformationIT.java
  alfresco-transformer-base/src/main/java/org/alfresco/transformer/util/MimetypeMap.java
  alfresco-transformer-base/src/test/java/org/alfresco/transformer/AbstractTransformerControllerTest.java
  pom.xml
Labels: PR: unreviewed

#239 ACS-113: Increase Office->PDF default size limits (via LibreOffice)
  alfresco-transform-libreoffice/alfresco-transform-libreoffice/src/main/resources/libreoffice_engine_config.json
Labels: PR: draft
