Repository Alfresco/alfresco-transform-core, pull requests merged in 2021-06, with the labels that each got.

#416 ATS-913: Added tests for GIF and PNG
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/java/org/alfresco/transformer/TikaMetadataExtractsIT.java
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quickIPTC.gif
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quickIPTC.gif_metadata.json
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quickIPTC.png
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quickIPTC.png_metadata.json
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/testJPEG_IPTC_EXT.jpg_metadata.json
  alfresco-transform-tika/alfresco-transform-tika/src/main/resources/IPTCMetadataExtractor_metadata_extract.properties
Labels: PR: unreviewed

#419 ATS-935 / ATS-936: Prep for T-Core 2.5.0 release
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml
  alfresco-transform-core-aio/alfresco-transform-core-aio/pom.xml
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/pom.xml
  alfresco-transform-imagemagick/alfresco-transform-imagemagick/pom.xml
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/pom.xml
  alfresco-transform-libreoffice/alfresco-transform-libreoffice/pom.xml
  alfresco-transform-misc/alfresco-transform-misc-boot/pom.xml
  alfresco-transform-misc/alfresco-transform-misc/pom.xml
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/pom.xml
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer/pom.xml
  alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml
  alfresco-transform-tika/alfresco-transform-tika/pom.xml
  alfresco-transformer-base/pom.xml
  pom.xml
Labels: PR: partially-approved

#418 ATS-935: Upgrade LibreOffice to 7.0.6 (from 6.3.5)
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/resources/application-default.yaml
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/Dockerfile
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/main/resources/application-default.yaml
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/test/java/org/alfresco/transformer/LibreOfficeTransformationIT.java
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/test/resources/quick.msg
  alfresco-transform-libreoffice/alfresco-transform-libreoffice/src/main/resources/libreoffice_engine_config.json
  docs/external-engine-configuration.md
  pom.xml
Labels: PR: partially-approved

#415 Refactor TikaController
  alfresco-transform-tika/alfresco-transform-tika-boot/src/main/java/org/alfresco/transformer/TikaController.java
Labels: PR: partially-approved

#428 ACS-1677 Provide file extension from JMS request if missing in SFS
  alfresco-transformer-base/src/main/java/org/alfresco/transformer/AbstractTransformerController.java
Labels: PR: reviewed-approved

#429 ATS-931 Release t-core 2.5.1 [trigger release]
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/Dockerfile
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/Dockerfile
  alfresco-transform-misc/alfresco-transform-misc-boot/Dockerfile
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/Dockerfile
  alfresco-transform-tika/alfresco-transform-tika-boot/Dockerfile
Labels: PR: reviewed-approved

#430 ATS: tweak top-level T-Core README
  README.md
Labels: PR: reviewed-approved
