Repository Alfresco/alfresco-transform-core, pull requests merged in 2021-05, with the labels that each got.

#397 ATS-892 Convert ExifTool separated strings into collections for ACS consumption
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/java/org/alfresco/transformer/TikaMetadataExtractsIT.java
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quick.tiff_metadata.json
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quickIPTC-EXT.jpg_metadata.json
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/quickIPTC-multi-creator.jpg_metadata.json
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/testJPEG_IPTC_EXT.jpg
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/resources/testJPEG_IPTC_EXT.jpg_metadata.json
  alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/metadataExtractors/IPTCMetadataExtractor.java
  alfresco-transform-tika/alfresco-transform-tika/src/main/java/org/alfresco/transformer/tika/parsers/ExifToolParser.java
  alfresco-transform-tika/alfresco-transform-tika/src/main/resources/parsers/external/config/exiftool-parser.xml
  alfresco-transform-tika/alfresco-transform-tika/src/test/java/org/alfresco/transformer/metadataExtractors/IPTCMetadataExtractorTest.java
  alfresco-transform-tika/alfresco-transform-tika/src/test/java/org/alfresco/transformer/tika/parsers/ExifToolParserTest.java
Labels: PR: unreviewed

#399 ATS-892 / ATS-909: Add IPTC model to ATS zip
  models/README.md
Labels: PR: partially-approved

#400 ATS-912 [trigger release] version 2.4.0
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml
  alfresco-transform-core-aio/alfresco-transform-core-aio/pom.xml
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/pom.xml
  alfresco-transform-imagemagick/alfresco-transform-imagemagick/pom.xml
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/pom.xml
  alfresco-transform-libreoffice/alfresco-transform-libreoffice/pom.xml
  alfresco-transform-misc/alfresco-transform-misc-boot/pom.xml
  alfresco-transform-misc/alfresco-transform-misc/pom.xml
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/pom.xml
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer/pom.xml
  alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml
  alfresco-transform-tika/alfresco-transform-tika/pom.xml
  alfresco-transformer-base/pom.xml
  pom.xml
Labels: PR: reviewed-approved

#401 ATS-912 [trigger release] 2.4.0
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/Dockerfile
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/Dockerfile
  alfresco-transform-misc/alfresco-transform-misc-boot/Dockerfile
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/Dockerfile
  alfresco-transform-tika/alfresco-transform-tika-boot/Dockerfile
Labels: PR: reviewed-approved

#408 ATS-909 / LOC-303: copy IPTC model properties (15 languages)
  models/iptc/iptc-model_cs.properties
  models/iptc/iptc-model_da.properties
  models/iptc/iptc-model_de.properties
  models/iptc/iptc-model_es.properties
  models/iptc/iptc-model_fi.properties
  models/iptc/iptc-model_fr.properties
  models/iptc/iptc-model_it.properties
  models/iptc/iptc-model_ja.properties
  models/iptc/iptc-model_nb.properties
  models/iptc/iptc-model_nl.properties
  models/iptc/iptc-model_pl.properties
  models/iptc/iptc-model_pt_BR.properties
  models/iptc/iptc-model_ru.properties
  models/iptc/iptc-model_sv.properties
  models/iptc/iptc-model_zh_CN.properties
Labels: PR: reviewed-approved

#409 ATS: Tweak Java Base Image references
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/Dockerfile
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/Dockerfile
  alfresco-transform-misc/alfresco-transform-misc-boot/Dockerfile
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/Dockerfile
  alfresco-transform-tika/alfresco-transform-tika-boot/Dockerfile
Labels: PR: partially-approved
