Repository Alfresco/alfresco-transform-core, pull requests merged in 2022-02, with the labels that each got.

#524 ACS-2499 Delete company release build stage.
  .travis.yml
  _ci/prepare_release_deploy.sh
  _ci/prepare_staging_deploy.sh
  docs/build-and-release.md
Labels: PR: unreviewed

#526 ACS-2498 Add coreVersion to T-Engine config
  _ci/source_clear.sh
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/java/org/alfresco/transformer/AIOController.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/main/resources/application-default.yaml
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerImageMagickTest.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerLibreOfficeTest.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerMiscTest.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerPdfRendererTest.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerTest.java
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/src/test/java/org/alfresco/transformer/AIOControllerTikaTest.java
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/src/main/resources/application-default.yaml
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/src/main/resources/application-default.yaml
  alfresco-transform-misc/alfresco-transform-misc-boot/src/main/java/org/alfresco/transformer/MiscController.java
  alfresco-transform-misc/alfresco-transform-misc-boot/src/main/resources/application-default.yaml
  alfresco-transform-misc/alfresco-transform-misc/src/main/java/org/alfresco/transformer/transformers/HtmlParserContentTransformer.java
  alfresco-transform-misc/alfresco-transform-misc/src/main/java/org/alfresco/transformer/transformers/SelectableTransformer.java
  alfresco-transform-misc/alfresco-transform-misc/src/main/java/org/alfresco/transformer/transformers/StringExtractingContentTransformer.java
  alfresco-transform-misc/alfresco-transform-misc/src/main/java/org/alfresco/transformer/transformers/TextToPdfContentTransformer.java
  alfresco-transform-misc/alfresco-transform-misc/src/test/java/org/alfresco/transformer/transformers/HtmlParserContentTransformerTest.java
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/src/main/resources/application-default.yaml
  alfresco-transform-tika/alfresco-transform-tika-boot/src/main/resources/application-default.yaml
  alfresco-transformer-base/src/main/java/org/alfresco/transformer/AbstractTransformerController.java
  alfresco-transformer-base/src/main/java/org/alfresco/transformer/TransformRegistryImpl.java
  alfresco-transformer-base/src/main/java/org/alfresco/transformer/util/RequestParamMap.java
  alfresco-transformer-base/src/test/java/org/alfresco/transformer/AbstractTransformerControllerTest.java
  pom.xml
Labels: PR: unreviewed

#532 ATS-977: Remove dependencies needed to build the `image-exiftool`
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile
  alfresco-transform-tika/alfresco-transform-tika-boot/Dockerfile
Labels: PR: partially-approved

#525 ACS-2497 T-Core: Accept DAU requests
  README.md
  alfresco-transform-misc/alfresco-transform-misc-boot/src/test/java/org/alfresco/transformer/MiscControllerTest.java
  alfresco-transform-tika/alfresco-transform-tika-boot/src/main/resources/templates/transformForm.html
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/java/org/alfresco/transformer/TikaControllerTest.java
  alfresco-transform-tika/alfresco-transform-tika-boot/src/test/java/org/alfresco/transformer/TikaHttpRequestTest.java
  alfresco-transformer-base/src/main/java/org/alfresco/transformer/AbstractTransformerController.java
  alfresco-transformer-base/src/test/java/org/alfresco/transformer/AbstractHttpRequestTest.java
  alfresco-transformer-base/src/test/java/org/alfresco/transformer/AbstractTransformerControllerTest.java
Labels: PR: reviewed-approved

#537 ATS-981 Avoid CVE-2022-23181 with spring-boot-starter-web 2.6.3
  pom.xml
Labels: PR: unreviewed

#436 ATS-864: Switch from fabric8 to docker mvn plugin
  .github/dependabot.yml
  alfresco-transform-core-aio/alfresco-transform-core-aio-boot/pom.xml
  alfresco-transform-core-aio/alfresco-transform-core-aio/pom.xml
  alfresco-transform-imagemagick/alfresco-transform-imagemagick-boot/pom.xml
  alfresco-transform-imagemagick/alfresco-transform-imagemagick/pom.xml
  alfresco-transform-libreoffice/alfresco-transform-libreoffice-boot/pom.xml
  alfresco-transform-libreoffice/alfresco-transform-libreoffice/pom.xml
  alfresco-transform-misc/alfresco-transform-misc-boot/pom.xml
  alfresco-transform-misc/alfresco-transform-misc/pom.xml
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer-boot/pom.xml
  alfresco-transform-pdf-renderer/alfresco-transform-pdf-renderer/pom.xml
  alfresco-transform-tika/alfresco-transform-tika-boot/pom.xml
  alfresco-transform-tika/alfresco-transform-tika/pom.xml
  alfresco-transformer-base/pom.xml
  pom.xml
Labels: PR: partially-approved

#539 ACS-2587 Include directAccessUrl in T-Config if supported
  alfresco-transform-core-aio/alfresco-transform-core-aio/src/main/java/org/alfresco/transformer/AIOTransformRegistry.java
  alfresco-transformer-base/src/main/java/org/alfresco/transformer/TransformRegistryImpl.java
  pom.xml
Labels: PR: unreviewed
