Repository Alfresco/alfresco-transform-core, pull requests merged in 2023-03, with the labels that each got.

#747 ACS-4739 Fix intermittent tests failures due to CustomTransformers
  engines/base/src/test/java/org/alfresco/transform/base/TransformControllerAllInOneTest.java
  engines/base/src/test/java/org/alfresco/transform/base/transform/FragmentHandlerTest.java
Labels: PR: partially-approved

#749 ACS-4769 Bump alfresco/alfresco-base-java to Rocky Linux 8.7
  engines/aio/Dockerfile
  engines/example/Dockerfile
  engines/imagemagick/Dockerfile
  engines/libreoffice/Dockerfile
  engines/misc/Dockerfile
  engines/pdfrenderer/Dockerfile
  engines/tika/Dockerfile
Labels: PR: partially-approved

#752 Feature/acs 4460 mtls support
  engines/base/src/main/java/org/alfresco/transform/base/config/MTLSConfig.java
  engines/base/src/test/java/org/alfresco/transform/base/MtlsTestUtils.java
Labels: PR: partially-approved

#766 Feature/acs 4839 mtls in deprecated module
  deprecated/alfresco-transformer-base/src/main/java/org/alfresco/transformer/config/WebApplicationConfig.java
Labels: PR: partially-approved

#769 Acs 4929 release version
  deprecated/alfresco-transformer-base/pom.xml
  engines/aio/pom.xml
  engines/base/pom.xml
  engines/example/pom.xml
  engines/imagemagick/pom.xml
  engines/libreoffice/pom.xml
  engines/misc/pom.xml
  engines/pdfrenderer/pom.xml
  engines/tika/pom.xml
  model/pom.xml
  pom.xml
Labels: PR: partially-approved

#768 ATS-996: TIFF to PDF - invalid output format
  engines/aio/src/test/java/org/alfresco/transform/aio/AIOTikaTest.java
  engines/misc/src/main/java/org/alfresco/transform/misc/transformers/ImageToPdfTransformer.java
  engines/misc/src/main/resources/misc_engine_config.json
  engines/misc/src/test/java/org/alfresco/transform/misc/transformers/ImageToPdfTransformerTest.java
  engines/misc/src/test/java/org/alfresco/transform/misc/util/ArgumentsCartesianProduct.java
  model/src/main/java/org/alfresco/transform/common/RequestParamMap.java
Labels: PR: unreviewed

#770 [ACS-4460] add no hostname verification remove com.google.collections…
  deprecated/alfresco-transformer-base/pom.xml
  deprecated/alfresco-transformer-base/src/main/java/org/alfresco/transformer/config/MTLSConfig.java
  engines/aio/pom.xml
  engines/base/pom.xml
  engines/base/src/main/java/org/alfresco/transform/base/config/MTLSConfig.java
Labels: PR: reviewed-approved

#775 ACS-4460: Release T-Core (T-Engines) 3.1.0-A5 [release], snakeyaml ve…
  .github/workflows/ci.yml
  pom.xml
Labels: PR: unreviewed
